import type { Metadata } from "next";
import Image from "next/image";
import Link from "../components/SafeLink";
import { Breadcrumbs } from "../components/Breadcrumbs";
import { JsonLd } from "../components/JsonLd";
import { MobileActionBar } from "../components/MobileActionBar";
import { PageCta } from "../components/PageCta";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";
import { SITE_URL } from "../../lib/site-data";
import { breadcrumbSchema, businessSchema, schemaGraph } from "../../lib/schema";

export const metadata: Metadata = { title: "Our Story | LAP Services", description: "Meet Layra, the founder of LAP Services, and learn how experience, family and genuine care shape our Gold Coast cleaning business.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  const schema = schemaGraph(businessSchema(), breadcrumbSchema([{ name: "Home", path: "/" }, { name: "About", path: "/about" }]), { "@type": "AboutPage", url: `${SITE_URL}/about`, mainEntity: { "@id": `${SITE_URL}/#business` } });
  return <><JsonLd data={schema} /><SiteHeader /><main>
    <header className="about-hero content-shell"><div><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "About" }]} /><span className="section-kicker">Our Story</span><h1>A cleaning business built from experience, family and a genuine love for what we do.</h1><p>My name is Layra, and I’m the founder of LAP Services.</p><p>For more than eight years, I’ve worked in the cleaning industry, building my experience from the ground up across residential, commercial and hospitality environments.</p><Link className="button button-primary" href="/#quote">Get my free quote</Link></div><Image src="/images/lap-cleaning-team-gold-coast.jpg" alt="Layra from LAP Services on the Gold Coast" width={900} height={1125} priority sizes="(max-width: 900px) 100vw, 44vw" /></header>
    <section className="about-story content-shell"><div><span className="section-kicker">Experience from every angle</span><h2>More than eight years learning what great cleaning really means.</h2></div><div><p>I’ve been a cleaner, a housekeeper, a supervisor and a manager. I’ve personally worked in homes, hotels, shopping centres and large-scale cleaning operations, learning the industry from every angle along the way.</p><p>Over the years, I’ve learned that great cleaning is about much more than knowing which products to use or how to get a job done. It’s about reliability, attention to detail, communication and understanding that every home, and every person, is different.</p></div></section>
    <section className="values-band"><div className="content-shell"><article><span>01</span><h3>Why LAP Services?</h3><p>LAP Services was born from something very personal. Becoming a mother had always been one of my biggest dreams. When my son was born, I knew I wanted to continue working and building my career, but I also wanted to be present for his childhood and be part of those everyday moments that go by far too quickly.</p><p>I wanted to create something of my own, a business that would allow me to work while still being there for my family.</p></article><article><span>02</span><h3>From a small beginning</h3><p>And that’s where LAP Services began. I wanted to bring together everything I had learned throughout my career, while creating a company built around the values that matter most to me: quality, trust, and genuine care.</p><p>LAP Services started very small, just my mum and me. Little by little, we’ve grown, while keeping the personal care and attention to detail that have always been at the heart of LAP Services.</p></article><article><span>03</span><h3>A team built on trust</h3><p>Today, we are a small and dedicated team, and I’m still personally involved in the day-to-day running of LAP Services. I stay directly connected with our clients and take the time to understand what matters most to each home.</p><p>I also personally interview and train our cleaners, and every member of our team completes a trial in my own home before working with our clients.</p></article></div></section>
    <section className="about-story content-shell"><div><span className="section-kicker">Cleaning with care</span><h2>Every home is different. That’s why we listen.</h2></div><div><p>This is important to me because I know what it feels like to be on both sides. I know how important it is to feel comfortable and confident when someone is coming into your home. And I also know how important it is for cleaners to feel respected, appreciated and supported for the work they do.</p><p>At LAP Services, we don’t believe in a one-size-fits-all approach to cleaning. Every home is different. Every family has different routines, priorities and expectations. What matters most to one client may be completely different for another.</p><p>We take the time to understand your priorities and tailor our service around your home and the things that matter to you.</p><p>For us, cleaning isn’t just about making a house look clean. It’s about trust. It’s about care. It’s about the little details. And it’s about making someone’s day a little easier.</p><p>LAP Services is something I’ve built with a lot of love — for my family, for our clients and for the people who work alongside me.</p><p>We started small, but we’re incredibly proud of what we’re building, and we’re committed to growing while keeping the personal care that brought us here in the first place.</p><p>Thank you for being here, and for considering LAP Services for your home.</p><p><strong>Layra</strong><br />Founder, LAP Services.</p></div></section>
    <PageCta title="Tell LAP what your property needs." />
  </main><SiteFooter /><MobileActionBar /></>;
}
